stages:
  - sonar

job_sonar:
  stage: sonar
  script:
    - sonar-scanner
        -Dsonar.projectName=${CI_PROJECT_NAME}
        -Dsonar.projectKey=${CI_PROJECT_NAME}
        -Dsonar.branch.name=dev
        -Dsonar.sources=.
        -Dsonar.exclusions=**/*.less,**/assets/**
  tags:
    - java-sonar
